title: CL Capital
description: > # this means to ignore newlines until "baseurl:"
 Official CL Capital's website
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "clcapital.net" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: RealCLCapital

# Author Settings
author: CL Capital # add your name
author-img: favicon/apple-touch-icon-144x144.png # add your photo
about-author: CL Capital's ideas are NOT investment advice nor recommendations of any kind. Stock/commodity/forex markets are inherently risky.
social-twitter: RealCLCapital
social-facebook: # add your Facebook handle
social-github: # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: clcapitalofficial@gmail.com

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-analytics

  # Disqus
discus-identifier: clcapital

# Tracker
google_analytics: UA-185723935-1

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
